import os
from fpdf import FPDF
from datetime import datetime

class PDFReport(FPDF):
    def header(self):
        # Logo placeholder (Optional: if the user has a logo, else just text)
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(37, 99, 235) # Blue
        self.cell(0, 15, 'Financial Risk AI - Official Report', border=False, align='C', new_x="LMARGIN", new_y="NEXT")
        self.set_line_width(0.5)
        self.set_draw_color(37, 99, 235)
        self.line(10, 25, 200, 25)
        self.ln(10)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by AI Underwriter on {datetime.now().strftime("%Y-%m-%d %H:%M")}', align='C')

def generate_pdf_report(applicant_data: dict, probability: float, ai_advice: str) -> bytes:
    """
    Generates a professional PDF report summarizing the loan risk assessment.
    Returns the PDF as a byte string.
    """
    pdf = PDFReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # Fonts
    pdf.set_font("Helvetica", size=12)

    # Risk Decision Section
    pdf.set_font("Helvetica", 'B', 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, 'Risk Assessment Decision', new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("Helvetica", size=12)
    pdf.set_text_color(50, 50, 50)
    is_approved = probability < 0.5
    decision_text = "APPROVED" if is_approved else "REJECTED (High Risk)"
    
    if is_approved:
        pdf.set_text_color(22, 101, 52) # Green
    else:
        pdf.set_text_color(153, 27, 27) # Red
        
    pdf.set_font("Helvetica", 'B', 14)
    pdf.cell(0, 10, f'Final Status: {decision_text}', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", size=12)
    pdf.cell(0, 10, f'Estimated Default Probability: {probability * 100:.1f}%', new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Applicant Profile Section
    pdf.set_font("Helvetica", 'B', 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, 'Applicant Profile Summary', new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", size=12)
    
    col_width = 90
    row_height = 8

    # Table Header
    pdf.set_font("Helvetica", 'B', 11)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(col_width, row_height, "Attribute", border=1, fill=True)
    pdf.cell(col_width, row_height, "Value", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", size=11)
    # Define fields to display cleanly
    display_fields = [
        ("Age", f"{applicant_data.get('person_age')} years"),
        ("Annual Income", f"INR {applicant_data.get('person_income'):,.2f}"),
        ("Employment Length", f"{applicant_data.get('person_emp_length')} years"),
        ("Home Ownership", str(applicant_data.get('person_home_ownership'))),
        ("Requested Loan Amount", f"INR {applicant_data.get('loan_amnt'):,.2f}"),
        ("Loan Intent", str(applicant_data.get('loan_intent'))),
        ("Debt-to-Income Ratio", f"{applicant_data.get('loan_percent_income')*100:.1f}%"),
        ("Credit History Length", f"{applicant_data.get('cb_person_cred_hist_length')} years")
    ]

    for key, value in display_fields:
        pdf.cell(col_width, row_height, key, border=1)
        pdf.cell(col_width, row_height, value, border=1, new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(10)

    # AI Underwriter Notes Section
    pdf.set_font("Helvetica", 'B', 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, 'AI Underwriter Analysis', new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(50, 50, 50)
    
    # Process the Markdown text somewhat (fpdf2 supports basic html or we can just print plain text)
    # For robust text handling, multi_cell is good.
    clean_advice = ai_advice.replace("**", "") # strip bold for basic PDF
    pdf.multi_cell(0, 7, clean_advice)
    
    return bytes(pdf.output())
